CHANNEL_ID = -1005067561822

CHANNELS = {
    -1003259505746: "https://t.me/+2AyzU2pm8y00NDc6"
}

private_channel_ids = {3117077473, 3259505746} 
 
VIP_PRICE = {
    "USDT": 0.3,
    "TON": 1.5,
    "BTC": 0.0001,
    "ETH": 0.001,
    "BNB": 0.01,
    "LTC": 0.02,
    "DOGE": 50,
    "TRX": 10,
    "NOT": 2,
}

CURRENCY_PRICES = {
    "1_day": {
        "TON": 0.5,
        "BTC": 0.0001,
        "ETH": 0.001,
        "USDT": 2,
        "BNB": 0.01,
        "LTC": 0.02,
        "DOGE": 50,
        "TRX": 10,
        "NOT": 2,
    },
    "30_days": {
        "TON": 2.5,
        "BTC": 0.001,
        "ETH": 0.01,
        "USDT": 8.5,
        "BNB": 0.1,
        "LTC": 0.1,
        "DOGE": 200,
        "TRX": 30,
        "NOT": 10,
    },
    "1_year": {
        "TON": 3.0,
        "BTC": 0.005,        "ETH": 0.05,
        "USDT": 10.10,
        "BNB": 0.5,
        "LTC": 0.5,
        "DOGE": 500,
        "TRX": 100,
        "NOT": 50,
    },
}

SESSION_DIR = 'Session'
bot_token = '8365548858:AAEbN_q9BEB4xrmf9aPx11rlcAj0x8c9BQI'   
admin_chat_ids = ['8299768278']
CRYPTO_PAY_TOKEN = '485913:AAthES9C4Gwk64pGwNwjAHRHteAHD7HKCDm'

senders = {
'semenova@ziggo.nl':'welkom01',
'xxklara11@vip.hr':'safari11',
'angel-anny@osnanet.de':'friends',
'pbangma@ziggo.nl':'Osiris28',
'weerd.dekei@ziggo.nl':'welkom01',
'lscheung@ziggo.nl':'welkom',
'jeroen1alberts@ziggo.nl':'Dewiislief09062011',
'ingrid-felix@ziggo.nl':'Welkom01',
'dietrich.enns@osnanet.de':'30041972',
'oudenes@ziggo.nl':'zeldzaam',
'vosjo@ziggo.nl':'banket43',
'd.j.molenaar@ziggo.nl':'Sjaak_1980',
'hassan1@ziggo.nl':'123456',
        "huyznaet06@gmail.com": "cyeb pnyi ctpj xxdx",
    "alabuga793@gmail.com": "tzuk rehw syaw ozme",
    
"dlatt6677@gmail.com": "usun ruef otzx zcrh",
"edittendo0@gmail.com": "mzdl lrmx puyq epur",
"shshsbsbsbwbwvw@gmail.com": "jqrx qivo qxjy jejt",
"IvanKarma2000@gmail.com": "irlr cggo xksq tlbb",
"misha28272727@gmail.com": "kgwqxvkgjyccibkm",
"vladimiradmiralov664@gmail.com": "papq hkip geao rkuz",
"trevorzxasuniga214@gmail.com": "egnr eucw jvxg jatq",
"dellapreston50@gmail.com": "qoit huon rzsd eewo",
"neilfdhioley765@gmail.com": "rgco uwiy qrdc gvqh",
"samuelmnjassey32@gmail.com": "lgct cjiw nufr zxjg",
"segapro72@gmail.com": "ubmq pbrt ujqy orhf",
"kurokopotok@gmail.com": "pxww ewut uffz ufpu",
"kalievutub@gmail.com": "jlwb otxo mppi jvdh",
"snosakka07@gmail.com": "yiro khva gafc lujr",
"prosega211@gmail.com": "fnrz rkrp nrwy yaig",
"qwaerlarp@gmail.com": "zrzx siyf ukvm ctjp",
"segatel093@gmail.com": "fsma qetz gvmp pqrm",
"irina15815123@gmail.com": "fmre mxne ncaw gnke",
"disgeugh482@gmail.com": "ufet dwko fadg crax",
"germanalexandrovich12345678@gmail.com": "tsln hvmz mipp kmwh",
"bl89222099674@gmail.com": "yjru yftj zihu nyrz",
"psega0892@gmail.com": "vhrr hiso npgm xnoi",
"noakk1843@gmail.com": "mvqo rfrv cjht vppo",
"mak091ov@gmail.com": "hhli muyx nqju wlkk",
"ilya228smirn0@gmail.com": "faex guxl rlsx tvyc",
"demidivivan548@gmail.com": "izky pqsm xmxk vgod",
"zedrenskijvitalij@gmail.com": "javb kkcu znxe ykdj",
"tatanamorinskaa@gmail.com": "cjig kaxt tijl ndre",
"ivanplutalov543@gmail.com": "xsvm ewki dhfz qqkh",
"editt1345@gmail.com": "hezf xuel hzvz jzur",
"dlatt7055@gmail.com": "tpzd nxle odaw uqwf",
"dlyabravla655@gmail.com": "kprn ihvr bgia vdys",
"allisonikse1922@gmail.com": "tozo xrzu qndn mwuq"
'rlwmulkens@ziggo.nl':'Mulkens1',
'j.wijnand@ziggo.nl':'Wijnand12!',
'margriet.brouwer@ziggo.nl':'34533453',
'hjellema@ziggo.nl':'LS87i3',
'enschede@ziggo.nl':'twente123',
'maikel.smit@ziggo.nl':'welkom01.',
'gp.breed@ziggo.nl':'Gerard1952',
'l.begas@ziggo.nl':'refugee3',
'jwblanksma@ziggo.nl':'joop2706',
'kacper@ziggo.nl':'shotshot',
'w.sevenstern@ziggo.nl':'Poppie32',
'rjrlindeman@ziggo.nl':'rjrl1976',
'maartenvansoest@ziggo.nl':'Gateway1',
'geertschepers.nl@ziggo.nl':'Geert.01',
'hutjeopdehei12@ziggo.nl':'trutje01',
'rolfdoedens@ziggo.nl':'klmn118092',
'rtbokum@ziggo.nl':'Velsatis01',
'barsik32@ziggo.nl':'shiva-1',
'janina.hegmanns2@osnanet.de':'9BwcxXeC',
'fransjoosen@ziggo.nl':'Joosen1949.',
'margriet.dijkshoorn@ziggo.nl':'Margriet01',
's.buhr@osnanet.de':'yebyzmtH1',
'a.roemers@ziggo.nl':'welkom01',
'humphrey@ziggo.nl':'welkom01',
'a.de.haan2@ziggo.nl':'harlingen2',
'abruinsma@ziggo.nl':'welkom01',
'keijser.w@ziggo.nl':'maikel1994',
'fokkejansma@ziggo.nl':'pontiac1',
'sylviayellowlunarsun@ziggo.nl':'Sjs27027',
'kerstin.oliver.jocksch@osnanet.de':'kinder4',
'memager@ziggo.nl':'Mager1',
'anton.versteeg@ziggo.nl':'Patroon-1',
'p.brolato@ziggo.nl':'welkom',
'vlinder124@ziggo.nl':'Hovawart01',
'niels.v.klaveren@ziggo.nl':'klerekast24',
'c.wonderwater@ziggo.nl':'1nouja',
'j.vdkooi@ziggo.nl':'jeroen01',
'wil.terreehorst@ziggo.nl':'corvette1',
'jeannevandeven@ziggo.nl':'Jeanne1940',
'leogerlag@ziggo.nl':'timmie51',
'jw-jansen@ziggo.nl':'welkom123',
'nanda.horn@ziggo.nl':'Stallen2008',
'wjvandenderen@ziggo.nl':'welkom',
'gerbenpannen@ziggo.nl':'gbvg41',
'allthatjazz@ziggo.nl':'jazzmenow',
'wimeelsing@ziggo.nl':'Pvmlkd37',
'timbomers@ziggo.nl':'53451984',
'h-nieman@ziggo.nl':'Hendrik1',
'amarinsdoevendans@ziggo.nl':'whucwlf4',
'wout.haf@ziggo.nl':'loeloe123',
'ibogers@ziggo.nl':'Aardvarken21!',
'tenpas@ziggo.nl':'ij9ndr5X',
'ahovenkamp@ziggo.nl':'lesbos2010',
'viola.huelse@osnanet.de':'huelse',
'funjet@ziggo.nl':'Funjet123',
's.boomsma@ziggo.nl':'Gs30533053.',
'fredhartman@ziggo.nl':'fred1965',
'dstruiksma@ziggo.nl':'welkom01',
'kloeckwibo@ziggo.nl':'Martine-77',
'jamhommes@ziggo.nl':'Phily001',
'mantelpieter@ziggo.nl':'Hakketak01',
'jgwestenberg@ziggo.nl':'Vuurtoren53',
'g.beusekom3@ziggo.nl':'Yoy90299',
'peter.schielen@ziggo.nl':'uh38ub',
'p_visser@ziggo.nl':'welkom01',
'sharlove@ziggo.nl':'10031986',
'wangosl@ziggo.nl':'mansaray123',
'margie1964@ziggo.nl':'Margie1964!',
'sufridor_vvc@ziggo.nl':'Sufridor1982',
'van.bavel@ziggo.nl':'Sasja2001!',
'kuenen76@ziggo.nl':'cypress1',
'gwkoerts@ziggo.nl':'Nootdweer',
'f.v.empel@ziggo.nl':'frank1',
'w-brands@ziggo.nl':'3513brands',
'swfurster@ziggo.nl':'beertje256',
'basdenijs@ziggo.nl':'Basdenijs1',
'j-leijtnes@ziggo.nl':'welkom01',
'jatdc@ziggo.nl':'Freespace2',
'juliavantongeren@ziggo.nl':'Juultje123',
'tessa.houtzager@ziggo.nl':'Tessa1',
'emma.herber@osnanet.de':'peter50',
'andreas_hagedorn@osnanet.de':'Grafzahl70',
'cici2904@osnanet.de':'2023ro',
'weith@osnanet.de':'Gaertnerei',
'kissgirl@osnanet.de':'schnuffi1710',
'rene.osterbrink@osnanet.de':'kocham',
'michael.brown@osnanet.de':'32Vgh902',
'marc.livermore@osnanet.de':'129896114',
'katharina.schulz@osnanet.de':'rosa1999',
'maik-peters@osnanet.de':'snoopy',
'mightybat@vip.hr':'batmaN1808',
'pierre.kemna@osnanet.de':'osnapower',
'hansjoerg.kasselmann@osnanet.de':'Lirunda',
'tomica05@vip.hr':'LUCIJA0505',
'tsimun@vip.hr':'marina1010',
'davidjan@ziggo.nl':'Davidjan1',
'paul.woldendorp@ziggo.nl':'Alexander1',
'mareijn.willems@ziggo.nl':'welkom',
'mwalison@ziggo.nl':'Wachtwoord',
'clemente@osnanet.de':'2-kinder',
'daniel.kasper@osnanet.de':'am3l13',
'andrea.heilmann-menzel@osnanet.de':'ninoah',
'dominik.stein@osnanet.de':'240994',
'wsw.rheine@osnanet.de':'waldemar1',
'hartmut.buescher@osnanet.de':'drillinge',
'mbister@vip.hr':'rolex69',
'stefan.schubert@osnanet.de':'chausson',
'jaceluni@osnanet.de':'luca10',
'kurt.reffeld@osnanet.de':'BMNnQS',
'n.arlavi@vip.hr':'0607979',
'jensis@osnanet.de':'28061979',
'leandra@osnanet.de':'kasimir',
'schnati92@osnanet.de':'240292',
}

receivers = [
    'sms@telegram.org', 'dmca@telegram.org', 'abuse@telegram.org', 'sticker@telegram.org',
    'support@telegram.org', 'support@telegram.org', 'dmca@telegram.org', 'security@telegram.org',
    'sms@telegram.org', 'info@telegram.org', 'marta@telegram.org', 'spam@telegram.org', 'alex@telegram.org',
    'abuse@telegram.org', 'pavel@telegram.org', 'durov@telegram.org', 'elies@telegram.org', 'ceo@telegram.org',
    'mr@telegram.org', 'levlam@telegram.org', 'perekopsky@telegram.org', 'recover@telegram.org', 'germany@telegram.org',
    'hyman@telegram.org', 'qa@telegram.org', 'Stickers@telegram.org', 'ir@telegram.org', 'vadim@telegram.org',
    'shyam@telegram.org', 'stopca@telegram.org', '>support@telegram.org', 'ask@telegram.org', '125support@telegram.org', 'me@telegram.org', 'enquiries@telegram.org', 'api_support@telegram.org', 'marketing@telegram.org', 'ca@telegram.org', 'recovery@telegram.org', 'http@telegram.org', 'corp@telegram.org', 'corona@telegram.org', 'ton@telegram.org', 'sticker@telegram.org'
]

smtp_servers = {
                "gmail.com": ("smtp.gmail.com", 587),
                "ziggo.nl": ("smtp.ziggo.nl", 587),
                "yandex.ru": ("smtp.yandex.ru", 587),
                "mail.ru": ("smtp.mail.ru", 587),
                "rambler.ru": ("smtp.rambler.ru", 587),
                "outlook.com":("smtp.office365.com", 587),
                "uhserver.com":("smtps.uhserver.com", 587),
                "vip.hr":("mail.vip.hr", 587),
                "mchsi.com":("smtp.mchsi.com", 587),
                "hotmail.com" : ("smtp.office365.com", 587),
                "live.com" : ("smtp.office365.com", 587),
                "yahoo.com" : ("smtp.mail.yahoo.com", 587),
                "aol.com" : ("smtp.aol.com", 587),
                "icloud.com" : ("smtp.mail.me.com", 587),
                "zoho.com" : ("smtp.zoho.com", 587),
                "fastmail.com" : ("smtp.fastmail.com", 587),
                "gmx.com" : ("smtp.gmx.com", 587),
                "bol.com.br" : ("smtp.bol.com.br", 587),
                "terra.com.br" : ("smtp.terra.com.br", 587),
                "free.fr" : ("smtp.free.fr", 587),
                "laposte.net" : ("smtp.laposte.net", 587),
                "btinternet.com" : ("mail.btinternet.com", 587),
                "btconnect.com" : ("mail.btinternet.com", 587),
                "qq.com" : ("smtp.qq.com", 587),
                "163.com" : ("smtp.163.com", 587),            
                "126.com" : ("smtp.126.com", 587),
                "sina.com" : ("smtp.sina.com", 587),
                "terra.com.mx" : ("smtp.terra.com.mx", 587),
                "sendgrid.net" : ("smtp.sendgrid.net", 587),
                "mailgun.org" : ("smtp.mailgun.org", 587),
                "postmarkapp.com" : ("smtp.postmarkapp.com", 587),
                "smtp.elasticemail.com" : ("smtp.elasticemail.com", 587),
                "mchsi.com" : ("smtp.mchsi.com", 587),
                "rambler.r" : ("smtp.rambler.ru", 587),
                "protonmail.com": ("mail.protonmail.com", 587),
                "proton.me": ("mail.protonmail.com", 587),
                "yandex.com": ("smtp.yandex.com", 587),
                "yandex.ua": ("smtp.yandex.ru", 587),
                "yandex.kz": ("smtp.yandex.ru", 587),
                "yahoo.co.uk": ("smtp.mail.yahoo.com", 587),
                "yahoo.de": ("smtp.mail.yahoo.com", 587),
                "ymail.com": ("smtp.mail.yahoo.com", 587),
                "rocketmail.com": ("smtp.mail.yahoo.com", 587),
                "seznam.cz": ("smtp.seznam.cz", 587),
                "wp.pl": ("smtp.wp.pl", 587),
                "o2.pl": ("poczta.o2.pl", 587),
                "orange.fr": ("smtp.orange.fr", 587),
                "sfr.fr": ("smtp.sfr.fr", 587),
                "wanadoo.fr": ("smtp.wanadoo.fr", 587),
                "web.de": ("smtp.web.de", 587),
                "gmx.net": ("smtp.gmx.net", 587),
                "gmx.de": ("smtp.gmx.de", 587),
                "mail.com": ("smtp.mail.com", 587),
                "libero.it": ("smtp.libero.it", 587),
                "alice.it": ("smtp.alice.it", 587),
                "virgilio.it": ("smtp.virgilio.it", 587),
                "naver.com": ("smtp.naver.com", 587),
                "daum.net": ("smtp.daum.net", 587),
                "nate.com": ("smtp.nate.com", 587),
                "hanmail.net": ("smtp.hanmail.net", 587),
                "5x2.de":("smtp.5x2.de", 587),
                "osnanet.de": ("smtp.osnanet.de", 587),
                "task.com.br": ("smtp.task.com.br", 587),
                "singnet.com": ("mail.singnet.com.sg", 25),
                "lds.net.ua": ("mail.lds.net.ua", 25),
                "montevideo.com.uy": ("mail.montevideo.com.uy", 25)
}

clients = [  
    {"name": "doom2", "api_id": 26898982, "api_hash": "1aff100a728735d53a0d9ce391fb9ed0"}
]
